[WIP] Mapping dynamic offset API
iree-org/iree-turbine pull request #272
Opened 2024-11-14 21:57 UTC by Hardcode84

New mapping API and test to show intended usage.

No lowering yet.

2024-11-14 23:11 UTC, harsh-nod commented
Please rebase on top of master to get the builders working.

2024-11-19 22:59 UTC, harsh-nod requested changes
Can you add a lit test so we can see what the IR should look like?

2024-11-19 22:59 UTC, harsh-nod commented on iree/turbine/kernel/wave/codegen.py
> +        static_pos = [0 for i in range(src.type.rank)]
minor: how about static_pos = [0] * src.type.rank

2024-11-20 02:06 UTC, Hardcode84 commented on iree/turbine/kernel/lang/wave_types.py
> +        | list[SymbolsMap, ...]
Yeah, good idea

2024-11-20 02:06 UTC, Hardcode84 commented on iree/turbine/kernel/lang/wave_types.py
> +        elif not isinstance(dynamic_val_mappings, (list, tuple)):
done

2024-11-20 02:06 UTC, Hardcode84 commented on iree/turbine/kernel/lang/wave_types.py
> +        if dynamic_val_mappings is None:
good idea

2024-11-20 02:07 UTC, Hardcode84 commented on iree/turbine/kernel/lang/wave_types.py
> +        self.dynamic_val_mappings = tuple(dynamic_val_mappings)
We can accept list or tuple, but inside the object I want to always store it as tuple.

2024-11-20 02:07 UTC, Hardcode84 commented on iree/turbine/kernel/lang/wave_types.py
> +        self.dynamic_vals = {self.dynamic_val(i): i for i in range(num_dyn_vals)}
done

2024-11-20 04:25 UTC, harsh-nod commented on tests/kernel/wave/wave_e2e_test.py
> +        device_randperm(shape[0], dtype=torch.int32)
makes sense, thanks!

2024-11-20 04:25 UTC, harsh-nod commented on iree/turbine/kernel/lang/wave_types.py
> +        self.dynamic_vals = {self.dynamic_val(i): i for i in range(num_dyn_vals)}
thanks

2024-11-20 04:26 UTC, harsh-nod commented on lit_tests/kernel/wave/codegen.py
> +        # CHECK:            %[[D19:.*]] = vector.gather %[[D10]][%[[C0]], %[[C0]]] [%[[D17]]], %[[D18]], %[[CST]] : memref<16x16xf16, strided<[16, 1], offset: ?>>, vector<16xindex>, vector<16xi1>, ve
thanks, nice to see the gather and how its being used :)

2024-11-20 04:27 UTC, harsh-nod approved these changes
lgtm! thanks!

2024-11-20 14:32 UTC, merged