[TKW] Distribute gpu tests
iree-org/iree-turbine pull request #353
Opened 2024-12-20 17:17 UTC by Hardcode84

2025-01-05 23:18 UTC, harsh-nod requested changes

2025-01-05 23:18 UTC, harsh-nod commented on iree/turbine/kernel/wave/utils.py
> +DEFAULT_GPU_DEVICE = None
Rather than have this as a global variable, can we instead pass this as an argument to the get_gpu_device_name(int) function? I am trying to see if we can reduce the number of command line arguments we need to export and this will also help when we get to distributed kernels (across multiple GPUs).

2025-01-06 18:20 UTC, Hardcode84 commented on .github/workflows/ci-tk.yaml
> +          WAVE_CACHE_ON=0 pytest -n 8 --capture=tee-sys -vv ./tests/kernel/wave/
Switch to pytest command line param

2025-01-06 19:36 UTC, harsh-nod commented on iree/turbine/kernel/wave/utils.py
> +DEFAULT_GPU_DEVICE = None
After a discussion, it makes sense to keep this for now to minimize changes across tests. But we will remove the WAVE_DISTRIBUTE_GPU_TESTS parameter and instead make it a pytest argument.

2025-01-06 22:29 UTC, harsh-nod approved these changes
lgtm!

2025-01-06 22:36 UTC, Hardcode84 commented
tests are still failing occasionally, btw

2025-01-07 00:31 UTC, merged